### ISSUE TITLE
Tokenizer not unconsuming X in in hex mode

### ISSUE THREAD

**Issue by dantti** [html5lib/html5lib-python#191]
Hi,

I'm implementing the WHATWG spec with C++/Qt and using your implementation as a reference is quite useful.
But I think I just found an error, 
in tokenizer.py line 172 there is:
self.stream.unget(charStack.pop())
sorry if my Python knowledge is mistaken but here
you only pop one char from the stack but in a '#Xabc' case
where the X stands for hexadecimals you sould
pop that too as the docs says: https://html.spec.whatwg.org/multipage/syntax.html#tokenizing-character-references
"If no characters match the range, then don't consume any characters (and unconsume the U+0023 NUMBER SIGN character and, if appropriate, the X character). This is a parse error; nothing is returned."
Best.

**Comment by dantti** [comment]
No actually you are unconsuming the X, but not the # number sign in that case...

**Comment by gsnedders** [comment]
So what we're interested in is `&#Xy` and `&#xy`? I imagine we're doing something black-box equivalent, because I'm pretty sure this works correctly.

**Comment by dantti** [comment]
I'm just saying that the docs says you should unconsume 1 or 2 chars depending if an X or x was found,
I think this would fix it (or at least follow what the specs  says):
if (hex):
    self.stream.unget(charStack.pop())
self.stream.unget(charStack.pop())

**Comment by gsnedders** [comment]
That won't work, because we only support a single character to be unconsumed. We appear to have the right behaviour, though, as I suspected.

**Comment by gsnedders** [comment]
See the `output = "&" + "".join(charStack)` on line 173, and line 216–223. Because none of the characters on the stack are characters that will change the tokeniser state, we directly append them instead of unconsuming them and reconsuming them, which is black-box equivalent. The validator.nu parser (and as a result the programmatic conversion of that which Gecko uses) doesn't have *any* unconsume and implements the whole tokeniser as a DFA.
