### ISSUE TITLE
cannot import name inputstream

### ISSUE THREAD

**Issue by abhisheklalnediya** [html5lib/html5lib-python#286]
It was working fine till html5lib (0.9999999)
But the latest is not good.
![selection_081](https://cloud.githubusercontent.com/assets/3649024/17047484/227bb9ec-4ffc-11e6-80de-da54d372ef64.png)
![selection_082](https://cloud.githubusercontent.com/assets/3649024/17047500/4f374fc8-4ffc-11e6-8766-82e84d9f8971.png)

**Comment by mhkuu** [comment]
I encountered this issue too, but I suppose this is an issue in [xhtml2pdf](https://pypi.python.org/pypi/xhtml2pdf) rather than in html5lib. The maintainer of xhtml2pdf however declared the project dead, and advises developers to switch to [WeasyPrint](https://github.com/Kozea/WeasyPrint). See [this discussion](https://groups.google.com/forum/#!topic/xhtml2pdf/PtG8J28Dwyk) for details.

**Comment by abhisheklalnediya** [comment]
Its not related to xhtml2pdf,
I am not able to import inputstream in my project too.

**Comment by sorter** [comment]
Changing 

     from html5lib import inputstream 

to

    from html5lib import _inputsream as inputstream 

has solved this for me.

**Comment by gsnedders** [comment]
`inputstream` was always intended to be private, hence why it's not supported as an argument to `parse` (or historically the tokenizer). I'd suggest avoid using it. (If you think you have a genuine use for it, let me know!)
