### ISSUE TITLE
update CHANGES.rst and AUTHORS.rst for 1.0 release

### ISSUE THREAD

**Issue by willkg** [html5lib/html5lib-python#382]
The `CHANGES.rst` and `AUTHORS.rst` files need to be updated for the 1.0 release.

**Comment by hugovk** [comment]
Here's a list of commits since last release to help with updating CHANGES.rst.

https://github.com/html5lib/html5lib-python/compare/0.999999999...master

**Comment by hugovk** [comment]
And here's a list of merges to master since 0.999999999:

69152dc Geoffrey.. 8 hours ago     Merge pull request #374 from willkg/307-html5parser
af35626 Will Kah.. 3 days ago      Merge pull request #379 from mvasilkov/patch-1
c4a85fc Will Kah.. 4 days ago      Merge pull request #377 from hugovk/upper-hex-in-css-colour
d595d0a Will Kah.. 5 days ago      Merge pull request #373 from willkg/371-reparse-private
1b515f5 Will Kah.. 5 days ago      Merge pull request #364 from jayvdb/codecov
85bc5fa Will Kah.. 4 weeks ago     Merge pull request #359 from jayvdb/add-appveyor
f4a6773 Will Kah.. 4 weeks ago     Merge pull request #355 from willkg/339-typo
69606e5 Will Kah.. 4 weeks ago     Merge pull request #332 from twm/update-docs
9f9dfdb Will Kah.. 5 weeks ago     Merge pull request #176 from RitwikGupta/master
194e101 Will Kah.. 5 weeks ago     Merge pull request #325 from scop/py36escseq
10e54c1 Will Kah.. 5 weeks ago     Merge pull request #327 from jvanasco/fix_updated_constants
48942a9 Will Kah.. 5 weeks ago     Merge pull request #352 from jdufresne/fix-test-failures
43aeaef Geoffrey.. 1 year, 4 months ago Merge pull request #285 from jayvdb/envmarker-monkeypatching
14d4851 Geoffrey.. 1 year, 5 months ago Merge pull request #275 from gsnedders/attr_order

Using:

`git log --merges --first-parent 0.999999999...master \
        --pretty=format:"%h %<(10,trunc)%an %<(15)%ar %s"
`

([git command info](https://stackoverflow.com/a/47213799/724176))

**Comment by hugovk** [comment]
That git command misses some.

This is a better list, 2016-07-15 was last release date:

https://github.com/html5lib/html5lib-python/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+created%3A%3E%3D2016-07-15
