### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by tgrrr** [html5lib/html5lib-python#390]
`html5lib.version is 1.0.1` produces the error

```
read_html('http://foo.com')

TypeError: __init__() got an unexpected keyword argument 'encoding'

```
Solution is to downgrade:`pip3 install -U html5lib=="0.9999999"`

It's a problem on SO [here](https://stackoverflow.com/q/46499808/3281978): and [here](https://stackoverflow.com/q/46499808/3281978)

It looks like it was referenced [as another issue but was closed](https://github.com/html5lib/html5lib-python/issues/281
)

Is it possible to fix this in version 1.0.1?

**Comment by mirh** [comment]
Bump

**Comment by willkg** [comment]
I don't see any evidence this is a problem with html5lib. Seems like this is a problem with whatever you're using that uses html5lib. There's no traceback in this issue, so it's hard to tell. The issues referenced are all issues with other software.

There aren't any specifics in this issues, so I can't be very helpful. Generally, upgrade the things you're using and make sure they either support recent versions of html5lib or are pinned to the versions they do support. Hope that helps!

Closing this out because there's nothing the html5lib project should do here.
