### ISSUE TITLE
tokenizer creates invalid " attribute

### ISSUE THREAD

**Issue by willkg** [html5lib/html5lib-python#407]
If there's an unclosed ", then the tokenizer will toss that in as an attribute name. Here's an example:

```
import html5lib
walker = html5lib.getTreeWalker('etree')
serializer = html5lib.serializer.HTMLSerializer()
parser = html5lib.HTMLParser()
dom = parser.parseFragment('<a href="http://example.com/"">')

print(serializer.render(walker(dom)))
```

With html5lib 1.0.1 in Python 2.7, that prints out:

```
<a "="" href="http://example.com/"></a>
```

That first attribute has a name of " and a value of "".

I'm pretty sure the problem is in the tokenizer in one of the attribute-related states, but that's as far as I've looked.

First question: Am I confused and that actually is valid HTML per the parsing algorithm?

Second question: If it's not valid HTML, what's the more correct thing to do with the extra "?

**Comment by gsnedders** [comment]
> First question: Am I confused and that actually is valid HTML per the parsing algorithm?

https://html.spec.whatwg.org/multipage/#before-attribute-name-state and then the attribute name state allow this (albeit with an unexpected-character-in-attribute-name parse error). In that specific case, you'll also get a missing-whitespace-between-attributes parse error due to the lack of whitespace after the previous attribute.

So this behaviour looks like the expected behaviour to me? The serialiser is outputting something that has parse errors, but it's also the direct serialization of that tree, and is what the [HTML fragment serialization algorithm](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments) gives for it (which we longer term want to match; #344).

(Reopen if you disagree/my hand execution of the parser is wrong.)
